return function()
	local icons = {
		ui = require("modules.utils.icons").get("ui"),
		diagnostics = require("modules.utils.icons").get("diagnostics"),
	}

	require("modules.utils").load_plugin("trouble", {
		auto_close = false,
		auto_preview = true,
		auto_refresh = true,
		focus = false,
		follow = true,
		indent_guides = true,
		max_items = 200,
		multiline = true,
		pinned = false,
		warn_no_results = true,
		open_no_results = false,
		win = {
			position = "bottom",
			size = { height = 10, width = 50 },
		},
		keys = {
			["q"] = "close",
			["<Esc>"] = "cancel",
			["r"] = "refresh",
			["<CR>"] = "jump",
			["<TAB>"] = "jump",
			["<C-x>"] = "jump_split",
			["<C-v>"] = "jump_vsplit",
			["<C-t>"] = "jump_tab",
			["o"] = { action = "jump", close = true },
			["P"] = "toggle_preview",
			["K"] = "hover",
			["p"] = "preview",
			["zM"] = "fold_close_all",
			["zm"] = "fold_close_all",
			["zR"] = "fold_open_all",
			["zr"] = "fold_open_all",
			["zA"] = "fold_toggle",
			["za"] = "fold_toggle",
			["k"] = "prev",
			["j"] = "next",
		},
		icons = {
			indent = {
				fold_open = icons.ui.ArrowOpen,
				fold_closed = icons.ui.ArrowClosed,
			},
			kinds = {
				Array = icons.ui.Array or "󰅪",
				Boolean = icons.ui.Boolean or "󰨙",
				Class = icons.ui.Class or "󰌗",
				Constant = icons.ui.Constant or "󰏿",
				Constructor = icons.ui.Constructor or "",
				Enum = icons.ui.Enum or "",
				EnumMember = icons.ui.EnumMember or "",
				Event = icons.ui.Event or "",
				Field = icons.ui.Field or "󰜢",
				File = icons.ui.File or "󰈙",
				Function = icons.ui.Function or "󰊕",
				Interface = icons.ui.Interface or "",
				Key = icons.ui.Key or "󰌋",
				Method = icons.ui.Method or "󰆧",
				Module = icons.ui.Module or "",
				Namespace = icons.ui.Namespace or "󰦮",
				Null = icons.ui.Null or "󰟢",
				Number = icons.ui.Number or "󰎠",
				Object = icons.ui.Object or "󰅩",
				Operator = icons.ui.Operator or "󰆕",
				Package = icons.ui.Package or "",
				Property = icons.ui.Property or "󰖷",
				String = icons.ui.String or "󰉿",
				Struct = icons.ui.Struct or "󱡠",
				TypeParameter = icons.ui.TypeParameter or "󰊄",
				Variable = icons.ui.Variable or "󰀫",
			},
		},
		modes = {
			diagnostics = {
				auto_open = false,
			},
			lsp_references = {
				auto_jump = false,
			},
		},
	})
end
